steps:
- id: "copy data file"
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', '-r', 'input/', 'gs://anz-raw-anz-bigdata/systemA/']

- id: "copy schema files"
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', '-r', 'schemas/', 'gs://anz-raw-anz-bigdata/systemA/schemas']

- name: 'gcr.io/cloud-builders/docker'
  id: 'precache_images'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull asia.gcr.io/$PROJECT_ID/${_IMAGE_NAME}; \
      exit 0

- name: 'gcr.io/cloud-builders/docker'
  id: 'build app'
  waitFor: ['precache_images']
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build -t anz-trans-modifier .
      exit 0

- name: 'gcr.io/cloud-builders/docker'
  id: 'tag image'
  waitFor: ['build app']
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker tag -t anz-trans-modifier:latest gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest
      exit 0

images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

substitutions:
  _IMAGE_NAME: anz-trans-modifier



